### ISSUE TITLE
Substitute serverUrl value in NLog.config from appsettings

### ISSUE THREAD

**Issue by SirGordon** [datalust/nlog-targets-seq#36]
Hello, is it possible to substitute serverUrl value in NLog.config from appsettings like this?
```
<nlog>
  <targets>
    <target name="seq" type="Seq" serverUrl="${appsetting:name=SeqEndpointUrl}" apiKey="some api key">
  </targets>
</nlog>
```
I've also tried to make nlog variable, it does not work as well ;/

However, `<property value/>` substitutoin works somehow:
```
<target name="seq" type="Seq" serverUrl="http://ihavetohardcodethis.com" apiKey="some api key">
  <property name="Source" value="${appsetting:name=Works}" />
</target>
```

**Comment by SirGordon** [comment]
**NLog version**
NLog, NLog Extended 4.5.9
NLog.Targets.Seq 1.0.0
Common.Logging.NLog444 3.4.1

**Platform**: .NET Framework 4.5

**Current NLog config**
```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Info" internalLogFile="C:\logs\nlog-internal.log"
      keepVariablesOnReload="true" >

  <extensions>
    <add assembly="NLog.Extended"/>
  </extensions>

  <variable name="SeqEndpointUrl" value="${appsetting:name=seq-endpoint-url}"/>

  <targets async="true">
    <!-- some other targets here -->
    <target name="seq" type="Seq" serverUrl="${SeqEndpointUrl}" apiKey="some api key">
      <property name="Source" value="${appsetting:name=seq-source}" />
      <property name="Login" value="${identity:authType=false}" />
      <property name="level" value="${level}" />
      <property name="Guid" value="${event-context:Guid}" />
      <property name="Type" value="${event-context:Type}" />
      <property name="User" value="${event-context:User}" />
      <property name="SQL" value="${event-context:SQL}" />
      <property name="Parameters" value="${event-context:Parameters}" />
      <property name="Elapsed" value="${event-context:Elapsed}" />
    </target>
  </targets>

  <rules>
    <logger name="Info" minlevel="Info" writeTo="fileInfo" />
    <logger name="Error" minlevel="Info" writeTo="fileError" />
    <logger name="Templates" minlevel="Info" writeTo="fileTemplates" />
    <logger name="Quartz.*" minlevel="Info" writeTo="fileQuartz" />
    <logger name="SQL" minlevel="Warn" writeTo="seq" />
    <logger name="SQL" minlevel="Info" writeTo="fileSQL" final="true" />
    <logger name="*" levels="Info,Warn,Error,Fatal" writeTo="seq" />
  </rules>
</nlog>
```

part of web.config:
```xml
<configuration>
  <appSettings>
    <add key="seq-source" value="Site_DEBUG"/>
    <add key="seq-endpoint-url" value="http://localhost:5341"/>
  </appSettings>
</configuration>
```

part of internal log:
```
2018-09-06 14:30:26.5117 Info NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c. File version: 4.5.9.8171. Product version: 4.5.9.
2018-09-06 14:30:26.7119 Error Error has been raised. Exception: System.UriFormatException: Invalid URI: The URI scheme is not valid.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at System.Net.WebRequest.Create(String requestUriString)
   at NLog.Targets.Seq.SeqTarget.PostBatch(IEnumerable`1 events)
   at NLog.Targets.Seq.SeqTarget.Write(IList`1 logEvents)
   at NLog.Targets.Target.Write(AsyncLogEventInfo[] logEvents)
   at NLog.Targets.Target.WriteAsyncThreadSafe(IList`1 logEvents)
   at NLog.Targets.Target.WriteAsyncLogEvents(IList`1 logEvents)
```

However, when i hardcode serverUrl value, it works.

**- What is the current result?**
Impossible to get `<variable value>` or serverUrl from web.config `<appSettings>`

**Comment by SirGordon** [comment]
https://github.com/NLog/NLog/issues/2904

**Comment by snakefoot** [comment]
Created #37 for you
